### ISSUE TITLE
Some issue with parsing received packet

### ISSUE THREAD

**Issue by mouryarahul** [bensherlock/micropython-unm3-pybd#1]
Hi @bensherlock, I'm not sure if this something to do with Firmware version of Nanomodem. I think using NMv3 (I never updated it). 
So in [unm3driver.py in line 500](https://github.com/bensherlock/micropython-unm3-pybd/blob/b7a274a21a70dfdbb67bff930cfb8a443f4f196c/main/unm3driver.py#L500), you have mentioned `# Expecting '#A255V21941\r\n'` however, I'm getting only `A255V21941`, which is I guess due to the `response_parser`. Because of this, [line 505](https://github.com/bensherlock/micropython-unm3-pybd/blob/b7a274a21a70dfdbb67bff930cfb8a443f4f196c/main/unm3driver.py#L505) is not behaving as intended. I'm observing similar behaviours in other functions too.
Thanks for your suggestion.

**Comment by mouryarahul** [comment]
Hi @bensherlock, I'm bit confused about the logic:
> ```python
> # Await the response
> response_parser.reset()
> awaiting_response = True
> timeout_time = timeout_helper.get_timeout_time(Nm3.RESPONSE_TIMEOUT)
> while awaiting_response and not timeout_helper.is_timedout(timeout_time):
>      resp_bytes = self._input_stream.read()
>         for b in resp_bytes:
>             if response_parser.process(b):
>                # Got a response
>                 awaiting_response = False
>                 break
> ```

Suppose, in the first try, `resp_bytes` is `None`, then iteration in `resp_bytes` generates the error:

> Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "uac_modem/main/unm3driver.py", line 649, in send_ping
TypeError: 'NoneType' object isn't iterable

What's your suggestion?

**Comment by bensherlock** [comment]
> Hi @bensherlock, I'm not sure if this something to do with Firmware version of Nanomodem. I think using NMv3 (I never updated it).
> So in [unm3driver.py in line 500](https://github.com/bensherlock/micropython-unm3-pybd/blob/b7a274a21a70dfdbb67bff930cfb8a443f4f196c/main/unm3driver.py#L500), you have mentioned `# Expecting '#A255V21941\r\n'` however, I'm getting only `A255V21941`, which is I guess due to the `response_parser`. Because of this, [line 505](https://github.com/bensherlock/micropython-unm3-pybd/blob/b7a274a21a70dfdbb67bff930cfb8a443f4f196c/main/unm3driver.py#L505) is not behaving as intended. I'm observing similar behaviours in other functions too.
> Thanks for your suggestion.

Even without the \r\n this would still work fine. So long as len is 5 or greater.

**Comment by bensherlock** [comment]
> Hi @bensherlock, I'm bit confused about the logic:
> 
> > ```python
> > # Await the response
> > response_parser.reset()
> > awaiting_response = True
> > timeout_time = timeout_helper.get_timeout_time(Nm3.RESPONSE_TIMEOUT)
> > while awaiting_response and not timeout_helper.is_timedout(timeout_time):
> >      resp_bytes = self._input_stream.read()
> >         for b in resp_bytes:
> >             if response_parser.process(b):
> >                # Got a response
> >                 awaiting_response = False
> >                 break
> > ```
> 
> Suppose, in the first try, `resp_bytes` is `None`, then iteration in `resp_bytes` generates the error:
> 
> > Traceback (most recent call last):
> > File "", line 1, in 
> > File "uac_modem/main/unm3driver.py", line 649, in send_ping
> > TypeError: 'NoneType' object isn't iterable
> 
> What's your suggestion?

Is this running on a PYBD using UART? Like as below? 

import machine
from uac_modem.main.unm3driver import MessagePacket, Nm3

uart = machine.UART(1, 9600, bits=8, parity=None, stop=1, timeout=100)
nm3_modem = Nm3(input_stream=uart, output_stream=uart)

I probably haven't seen this issue yet as the 100ms timeout was always plenty. Will add a test for None on resp_bytes.

**Comment by mouryarahul** [comment]
> > Hi @bensherlock, I'm not sure if this something to do with Firmware version of Nanomodem. I think using NMv3 (I never updated it).
> > So in [unm3driver.py in line 500](https://github.com/bensherlock/micropython-unm3-pybd/blob/b7a274a21a70dfdbb67bff930cfb8a443f4f196c/main/unm3driver.py#L500), you have mentioned `# Expecting '#A255V21941\r\n'` however, I'm getting only `A255V21941`, which is I guess due to the `response_parser`. Because of this, [line 505](https://github.com/bensherlock/micropython-unm3-pybd/blob/b7a274a21a70dfdbb67bff930cfb8a443f4f196c/main/unm3driver.py#L505) is not behaving as intended. I'm observing similar behaviours in other functions too.
> > Thanks for your suggestion.
> 
> Even without the \r\n this would still work fine. So long as len is 5 or greater.

Isn't that [line 500](https://github.com/bensherlock/micropython-unm3-pybd/blob/b7a274a21a70dfdbb67bff930cfb8a443f4f196c/main/unm3driver.py#L505) should be changed to `addr_string = resp_string[1:4]`?

**Comment by bensherlock** [comment]
Ah, no there should be a # still in there at the beginning.

**Comment by bensherlock** [comment]
The previous fix caught one issue but not the other one you mentioned regarding the response_parser and it missing the leading '#'. Will fix.

**Comment by bensherlock** [comment]
Tested with get_address(), the response_parser now returns the response string with the leading '#' such that extracting the address characters and converting to integer now behaves correctly.
